CC=gcc
multTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc5\headers5\headers5_2 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc5\src5\multTwoInt.c
addTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc5\headers5 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc5\src5\addTwoInt.c
main5.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc5\headers5 -I C:\Users\Andac\PycharmProjects\makefile-generator\tc5\headers5\headers5_2 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc5\main5.c
all: multTwoInt.o addTwoInt.o main5.o
	$(CC) multTwoInt.o addTwoInt.o main5.o -o hello