CC=gcc
main1.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc1\headers1 -I C:\Users\Andac\PycharmProjects\makefile-generator\tc1\headers1 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc1\main1.c
multTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc1\headers1 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc1\src1\multTwoInt.c
addTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc1\headers1 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc1\src1\addTwoInt.c
all: main1.o multTwoInt.o addTwoInt.o
	$(CC) main1.o multTwoInt.o addTwoInt.o -o hello