CC=gcc
unusedFunc.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc4\headers4 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc4\src4\unusedFunc.c
main4.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc4\headers4 -I C:\Users\Andac\PycharmProjects\makefile-generator\tc4\headers4 -I C:\Users\Andac\PycharmProjects\makefile-generator\tc4\headers4 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc4\main4.c
multTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc4\headers4 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc4\src4\multTwoInt.c
addTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc4\headers4 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc4\src4\addTwoInt.c
all: unusedFunc.o main4.o multTwoInt.o addTwoInt.o
	$(CC) unusedFunc.o main4.o multTwoInt.o addTwoInt.o -o hello