CC=gcc
main3.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc3\headers3 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc3\main3.c
multTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc3\headers3 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc3\src3\multTwoInt.c
addTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc3\headers3 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc3\src3\addTwoInt.c
all: main3.o multTwoInt.o addTwoInt.o
	$(CC) main3.o multTwoInt.o addTwoInt.o -o hello