CC=gcc
multTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc2 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc2\multTwoInt.c
main2.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc2 -I C:\Users\Andac\PycharmProjects\makefile-generator\tc2 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc2\main2.c
addTwoInt.o:
	$(CC) -I C:\Users\Andac\PycharmProjects\makefile-generator\tc2 -c C:\Users\Andac\PycharmProjects\makefile-generator\tc2\addTwoInt.c
all: multTwoInt.o main2.o addTwoInt.o
	$(CC) multTwoInt.o main2.o addTwoInt.o -o hello